#!/bin/sh

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}black .
${PREFIX}autoflake --in-place --recursive schema_registry tests setup.py
${PREFIX}isort .
