#!/bin/sh -e

export PREFIX=""
if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

set -x

${PREFIX}black schema_registry tests
${PREFIX}autoflake --in-place --recursive schema_registry tests setup.py
${PREFIX}isort schema_registry tests
