#!/bin/sh

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}black --line-length 120 .
${PREFIX}autoflake --in-place --recursive schema_registry tests setup.py
${PREFIX}isort -rc --line-width 120 .
