#!/bin/sh

./scripts/clean

VERSION=`cat setup.py | grep '__version__ =' | sed 's/__version__ = //' | sed 's/"//g'`

# # uploading to pypi
python setup.py sdist
twine upload dist/*

# # creating git tag
echo "Considering doing the following actions:"
echo "git tag -a v${VERSION} -m 'release previous-version → v${VERSION}'"
echo "git push origin v${VERSION}"

# deploy documentation
mkdocs gh-deploy
