#!/bin/bash -e

set -x

poetry run pytest --cov=schema_registry ${1} --cov-fail-under=87
poetry run codecov --token=$CODECOV_TOKEN
poetry run ruff schema_registry/ tests/
poetry run black --check --diff schema_registry tests
poetry run mypy schema_registry
