#!/bin/bash -e

set -o errexit

PYTHON_VERSION="3.10"

ARGS=""
if [[ $# -eq 2 ]]; then
  case "$1" in
    --python-version)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        PYTHON_VERSION=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    *) # preserve other arguments
      ARGS="$ARGS $1"
      shift
      ;;
  esac
fi

# set positional arguments in their proper place
eval set -- "$ARGS"

echo "Run tests using python" $PYTHON_VERSION
docker-compose build --build-arg PYTHON_VERSION=$PYTHON_VERSION

# run tests against schema registry server
docker-compose run --rm \
    -e CODECOV_TOKEN=${CODECOV_TOKEN} \
    schema-registry-client ./scripts/run-tests ${1-"./tests"} \

docker-compose down
