#!/bin/bash -e

set -o errexit

export SCHEMA_REGISTRY_URL=http://localhost:8081
export KAFKA_BOOSTRAP_SERVER_NAME=127.0.0.1
export KAFKA_BOOSTRAP_SERVER_PORT=9092
export SCHEMA_REGISTRY_SERVER=127.0.0.1
export SCHEMA_REGISTRY_SERVER_PORT=8081

./scripts/wait_for_services

poetry run pytest --cov=schema_registry ${1} --cov-fail-under=87
poetry run ruff schema_registry/ tests/
poetry run ruff format --check --diff schema_registry tests
poetry run mypy schema_registry
poetry run codecov --token=$CODECOV_TOKEN
